[theme]
primaryColor = "#2439f7"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1c24"
textColor = "#fafafa"

[server]
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info" 